# document configuration
nav:
  - Cookbook: index.md

  - App:
      - Mac App: app/Whats-in-my-Mac.md
      - Win10 App: app/Whats-in-my-Win10.md
      - iPad App: app/Whats-in-my-iPad.md
      - Android App: app/Whats-in-my-Android.md
      - Chrome Extensions: app/Whats-in-my-Chrome-extensions.md
      - Tampermonkey scripts: app/Whats-in-my-tampermonkey.md

  - Leetcode:
      - 20. Valid Parentheses: leetcode/valid_parentheses.md
      - 26. Remove Duplicates from Sorted Array: leetcode/Remove_Duplicates_from_Sorted_Array.md
      - 125.valid palindrome: leetcode/valid_palindrome.md

  - Data Structure & Algorithm:
      - complexity: algo/complexity.md
      - Two pointers: algo/two_pointers.md
      - Sort: algo/sort.md

  - Basic Knowledge:
      - How to Google: basic_knowledge/how_to_google.md
      - Learn double pinyin right now: basic_knowledge/double_pinyin.md

  - Data Science:
      - data science intro: data_science/data_science_intro.md
      - IPython intro: data_science/IPython_intro.md
      - NumPy intro: data_science/numpy_intro.md
      - Matplotlib intro: data_science/matplotlib_intro.md
      - Data Science tool chain: data_science/tool_chain.md

# Project information
site_name: "Cookbook"
site_description: "roseau knowledge database."
site_author: "roseauhan"
site_url: "https://roseauhan.github.io/cookbook/"

# Repository
repo_name: "Cookbook"
repo_url: "https://github.com/RoseauHan/cookbook/"

# Copyright
copyright: "Copyright &copy; roseau 2019 - 2020 "

# Theme Configuration
theme:
  name: "material"
  language: zh
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  logo: assets/favicon.ico

# Customization
extra:
  disqus: "roseauhan"
  manifest: "assets/manifest.webmanifest"
  social:
    - type: "github-alt"
      link: "https://github.com/roseauhan"
    - type: "twitter"
      link: "https://twitter.com/roseauhan"
    - type: "dribbble"
      link: "https://dribbble.com/roseauhan"
    - type: "rss"
      link: "https://roseauhan.github.io"

# Google Analytics
google_analytics:
  - "UA-XXXXXXXX-X"
  - "auto"

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - meta
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - git-revision-date-localized:
      type: iso_date

extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML"
