# document configuration
nav:
- Cookbook: index.md

- App:
  - Mac App: app/Whats-in-my-Mac.md
  - Win10 App: app/Whats-in-my-Win10.md
  - iPad App: app/Whats-in-my-iPad.md
  - Android App: app/Whats-in-my-Android.md


# Project information
site_name: 'Cookbook-roseau'
site_description: 'roseau knowledge database.'
site_author: 'roseauhan'
site_url: 'https://roseauhan.github.io/cookbook-material/'

# Repository
repo_name: 'Cookbook-roseau'
repo_url: 'https://github.com/RoseauHan/cookbook-material'

# Copyright
copyright: 'Copyright &copy; 2018 - 2019 roseauhan'

# Configuration
theme:
  name: 'material'
  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  # favicon: assets/images/favicon.ico
  logo: "https://i.loli.net/2019/08/11/ZNIuBreOtdp1XjG.png"


# Customization
extra:
  disqus: 'roseauhan'
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github-alt'
      link: 'https://github.com/roseauhan'
    - type: 'twitter'
      link: 'https://twitter.com/roseauhan'
    - type: 'dribbble'
      link: 'https://dribbble.com/roseauhan'
    - type: 'rss'
      link: 'https://roseauhan.github.io'

# Google Analytics
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - meta
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
